### ISSUE TITLE
textdomain argument

### ISSUE THREAD

**Issue by jamielsharief** [php/doc-en#1092]
From manual page: https://php.net/function.textdomain

---

Is this suppose to be `textdomain(string $domain): string`

**Comment by cmb69** [comment]
No. See the [parameter description](https://www.php.net/manual/en/function.textdomain.php#refsect1-function.textdomain-parameters):

> The new message domain, or null to get the current setting without changing it

**Comment by jamielsharief** [comment]
`$result = textdomain();`

PHP Warning:  textdomain() expects exactly 1 parameter, 0 given in /code/test.php on line 4

Warning: textdomain() expects exactly 1 parameter, 0 given in /code/test.php on line 4

**Comment by kamil-tekiela** [comment]
You are getting a warning (error in PHP 8) because you need to provide one argument to that function. The argument is not optional. It can be either string or null, but the argument must be provided. It looks like you are just confusing nullable arguments with optional arguments. 

Use this code and you won't get a warning:
```
$result = textdomain(null);
```

**Comment by jamielsharief** [comment]
I just realised my mistake, I was not paying attention. Thanks.
