### ISSUE TITLE
Documentation omission for PHP Migration from 5 to 7

### ISSUE THREAD

**Issue by alexNecroJack** [php/doc-en#1290]
An important change in foreach that is omitted in documentation
(https://www.php.net/manual/en/migration70.incompatible.php)
is that it also changed the way by-reference is handled.
You can no longer replace the item of the iteration by reference.

For example
```PHP
<?php
    $a = [
        ['id' => '1001'],
        ['id' => '190']
    ];
    
    foreach ($a ?: [] as &$b) {
        $b = [
          'id' => $b['id'],
          'text' => $b['id'],
        ];
    }
    var_export($a);
```

PHP 5 result:
```PHP
array (
  0 => 
  array (
    'id' => '1001',
    'text' => '1001',
  ),
  1 => 
  array (
    'id' => '190',
    'text' => '190',
  ),
)
```

PHP >=7 result:
```PHP
array (
  0 => 
  array (
    'id' => '1001',
  ),
  1 => 
  array (
    'id' => '190',
  ),
)
```

This change is not stated in the documentation.
I had trouble finding it in my code.

**Comment by alexNecroJack** [comment]
No, no, no, no. I'm really sorry, it seems I misunderstood the problem.

The problem is in this line "foreach ($a ?: [] as &$b) {"
this part of the code "$a ?: []".
In PHP 5, the result of this was **the variable** $a.
In PHP 7+, the result of this is the value **of the variable** $a,
and therefor the reference is not able to ever change the variable $a.

I don't know if this is "buggy", meaning open for misunderstandings,
in which case it should be noted in documentations somehow,
or if people seeing this "foreach ($a ?: [] as &$b) {" will most of the times
realize it's the value of the array is given for iteration, and therefor no documentation change is needed.

I also have no idea what terms to use to describe it, or where this info would be useful,
so I leave it up to the admins/contributors to use the message I delivered as they see fit.
(maybe just delete it)

**Comment by cmb69** [comment]
Yeah, the issue is iterating over the expression `$a ?: []` by reference. PHP 5 was more liberal  [when passing expressions by reference](https://3v4l.org/tJUSa); it seems to me that this was silently accepted for foreach was merely an oversight. I don't think that it is important to document that foreach behavior, but https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.error-handling.strict might need a fix, but considering https://3v4l.org/5AIrb, I'm not exactly sure.
