### ISSUE TITLE
In_array returns true when it should return false

### ISSUE THREAD

**Issue by runishkumar** [php/doc-en#1299]
From manual page: https://php.net/function.in-array

---
```
php > var_dump(in_array('a', [0,1,2,3,4,5,6,7,8,9]));
bool(true)
php >
```

I don't understand why `in_array` returns true for such a simple check. It does return false with third parameter true.
```
php > var_dump(in_array('a', [0,1,2,3,4,5,6,7,8,9], true));
bool(false)
php >
```

**Comment by kamil-tekiela** [comment]
It returns true because `'a' == 0` in PHP 7. https://3v4l.org/plpeH

This has changed in PHP 8, which I encourage you to use. Either way, this doesn't look like a valid bug report, so I am closing this issue. If you think something is not clear in the manual then please explain what you would like to see regarding the thrid parameter that would make it easier to understand. As of now it clearly states that it only checks values if the third parameter is false:
> If the third parameter strict is set to true then the in_array() function will also check the types of the needle in the haystack.
