### ISSUE TITLE
Europe/Kiev should be Europe/Kyiv

### ISSUE THREAD

**Issue by bknutson123** [php/doc-en#1319]

**Comment by cmb69** [comment]
This is an [upstream decision](https://github.com/eggert/tz/blob/2015b/europe#L3279-L3291).

**Comment by kamil-tekiela** [comment]
See relevant conversation upstream http://mm.icann.org/pipermail/tz/2018-October/026977.html

**Comment by sabernhardt** [comment]
The [timezone list](https://www.iana.org/time-zones) has not been updated since March, but an [April update](https://github.com/eggert/tz/blob/main/europe#L4118-L4133) indicates a change in the decision. This reflects [AP Style](https://blog.ap.org/announcements/an-update-on-ap-style-on-kyiv), too.

PR #851 updates the XML.
