### ISSUE TITLE
string return on *affected-rows methods

### ISSUE THREAD

**Issue by staabm** [php/doc-en#1483]
https://www.php.net/manual/en/mysqli.affected-rows.php Mentions the following note:

> If the number of affected rows is greater than the maximum int value (PHP_INT_MAX), the number of affected rows will be returned as a string.

Other similar functions don‘t contain the same note, e.g.
- db2_num_rows
- oci_num_rows 
- pdostatement::rowCount 
- sqlsrv_rows_affected
- … 

Does the same note apply to them and therefore they might also return `string` on big numbers?

**Comment by kamil-tekiela** [comment]
No.

On 32bit systems the number is converted from uint64_t to int32_t. See [PDO_MySQL](https://github.com/php/php-src/blob/master/ext/pdo_mysql/mysql_statement.c#L150). On 64 bit difference, the cast is from uint64_t to int64_t. 

I am not sure how exactly the other extensions deal with this but they all seem to be casting to ZEND_LONG. It might be that the numbers that exceed signed int (int64_t) are undefined behaviour. 

Anyway, the documentation seems to be correct. Sorry, if I didn't provide a more technical answer. Perhaps someone else can chime in to give a better explanation.

**Comment by cmb69** [comment]
> I am not sure how exactly the other extensions deal with this but they all seem to be casting to ZEND_LONG.

Hmm, that might be an issue on 32bit systems, though.

> I just tried inserting an unsigned bigint using mysqli and I got "%I64u" as a return of insert_id.

Ugh, that would be the format specifier printed out literally, what is not supposed to happen, but happens due to https://github.com/php/php-src/blob/2119ba215aacf0b3964694a34aa39037e032abf6/UPGRADING.INTERNALS#L98-L101. Apparently, the required update had [not been applied to ext/mysqli on Windows](https://github.com/php/php-src/blob/8200d667fbf66b388194a8e612e836a976f8496d/ext/mysqli/php_mysqli_structs.h#L130-L131). Bug.

**Comment by cmb69** [comment]
I'm going to close this ticket, since it is not really actionable as is. Please file new tickets, *if* these functions don't behave as documented.
