### ISSUE TITLE
openssl_random_pseudo_bytes can no longer return false

### ISSUE THREAD

**Issue by staabm** [php/doc-en#1729]
From manual page: https://php.net/function.openssl-random-pseudo-bytes

the docs mention 2 different return types for this method. the signature says `string` the long description is talking about a possible `false`. which one is correct? maybe it did even change recently with a recent php version and the changelog also needs an update?

![grafik](https://user-images.githubusercontent.com/120441/181723420-3b52d04a-32f6-4787-a779-b4f301dfe541.png)

---

**Comment by cmb69** [comment]
As of PHP 8.0.0, the canonical source of truth of the function signatures are the stub files. In this case, https://github.com/php/php-src/blob/php-8.0.0/ext/openssl/openssl.stub.php#L215-L216 says the return type is `string`. Since the manual is supposed to document the behavior as of PHP 7.0.0, we need to check the implementation, and indeed, prior to PHP 7.4.0, the function returned `false` on failure, while now it throws on failure.

**Comment by staabm** [comment]
thanks for the fast fix Christoph!
