### ISSUE TITLE
can `$dom->createElement` return `false`

### ISSUE THREAD

**Issue by staabm** [php/doc-en#1741]
### Description

the docs suggest createElement() might return false.

https://www.php.net/manual/en/domdocument.createelement.php

looking at the source makes me think there is only a single case which might return false

https://github.com/php/php-src/blob/c2a58ab07db1d004daa65646315d9bf63d208827/ext/dom/document.c#L529-L532
(This code snippet can be found several times within this file)

I tried triggering this line, but then I got a exception, see https://3v4l.org/L35Q6

I am wondering whether the return false is no longer possible and the signature should be updated?

### PHP Version

8.1.8

**Comment by cmb69** [comment]
> Unless we remove the option to have `::$strictErrorChecking===false`, we cannot change the signature.

Ugh, it's even worse. Besides the `INVALID_CHARACTER_ERR` issue (which depends on `::strictErrorChecking`), the method also returns `false` (regardless of `::strictErrorChecking`) in case `xmlNewDocNode()` fails (i.e. returns `NULL`). That renders the desciption of `::strictErrorChecking` wrong:

> Throws [DOMException](https://www.php.net/manual/en/class.domexception.php) on errors. Default to true.

Or is that an implementation error?

**Comment by nielsdos** [comment]
The implementation error of returning false on out-of-memory was fixed in 8.1 and above (8.0 unchanged): https://github.com/php/php-src/commit/c2a58ab07db1d004daa65646315d9bf63d208827
However, the same implementation error still exists for createElementNS in all versions. This should be fixed (but probably also on master-only because of the theoretical BC break).

After that the docs should be updated, along with a changelog item maybe? Looks like the changelog items for the changes of that commit are not present in the docs.
Even though this condition is very rare, I suppose we still want to add the changelog item for these changes done in 8.1.
What a mess.

**Comment by nielsdos** [comment]
You are right that the only way to get it to return false is by providing an invalid name.
The reason you got an exception instead of a false return value is because `strictErrorChecking` is by default `true`.
If you put it to false you can get it to return false on error: https://3v4l.org/CGM1H

So right now yes, the function can return false on error.
All of this strict error nonsense will go away when my spec compliance RFC lands.

**Comment by nielsdos** [comment]
I think there's nothing left here to do as shown by my previous comment.
