### ISSUE TITLE
PHP-Sodium - Aarch64 Packages

### ISSUE THREAD

**Issue by WDC** [php/doc-en#1834]
From manual page: https://php.net/book.sodium

---

I am attempting to install `php-sodium` for any version of PHP on CentOS Stream 8 on aarch64 (AWS Gravitron 2). The package does not exist, nor does it exist anywhere else.

Is there a timetable for getting ARM-compatible packages pushed-out for popular packages such as PHP-Sodium?

Thank you!

**Comment by nikic** [comment]
The PHP project has no involvement in packaging for Linux distributions -- you need to contact distro maintainers over appropriate channels.

For your specific case you're probably out of luck when it comes to pre-built packages, because Remi's repo does not provide aarch64 builds. CentOS 9 does have php-sodium though.
