### ISSUE TITLE
Wrong PHP version for mb_chr()

### ISSUE THREAD

**Issue by LMCom** [php/doc-en#1871]
From manual page: https://php.net/function.mb-chr

---
It states:

> (PHP 7 >= 7.2.0, PHP 8)

But it became available in PHP 7.1. I have it in PHP 7.1.33.

**Comment by cmb69** [comment]
`mb_chr()` has been introduced with commit https://github.com/php/php-src/commit/32383114d540c642222307b1c08535301ea376f2, which only made it to php-7.2.0RC1. https://heap.space/search?project=PHP-7.1&project=PHP-7.2&full=&defs=mb_chr&refs=&path=&hist=&type= confirms that it is not part of PHP 7.1. Maybe you have a patched PHP, or some userland fallback (perhaps due to the Symfony Polyfill / Mbstring Component).
