### ISSUE TITLE
CURLOPT_PASSWDFUNCTION and CURLOPT_MUTE no longer defined

### ISSUE THREAD

**Issue by ProceduralMan** [php/doc-en#1935]
From manual page: https://php.net/function.curl-setopt

---
Hi!
Seems those two options are no longer defined in PHP but are still showing on the man page:
CURLOPT_PASSWDFUNCTION
CURLOPT_MUTE in this case there is a warning about it being removed in cURL 7.15.5 but no sign that it is also non-existent in PHP

I think it should be better to remove them form the man page, given that they are no longer supported...

KR

**Comment by cmb69** [comment]
The manual is (currently) supposed to document all versions from PHP 7.0.0 to latest. Since PHP 7.0.0 [required only cURL ≥ 7.10.5](https://github.com/php/php-src/blob/bd289af9630f827728b32360bcd09a614aae8f23/ext/curl/config.m4#L41), we cannot yet remove `CURLOPT_MUTE`.

Regarding `CURLOPT_PASSWDFUNCTION`: this constant is apparently removed as of PHP 7.3.0, so this needs to be documented. Other than that, we cannot yet remove this option from the manual either.
