### ISSUE TITLE
http_build_query 3rd argument different results in PHP 7 vs 8

### ISSUE THREAD

**Issue by R2116** [php/doc-en#2108]
Hi there,

passing `null` as 3rd parameter results in different query strings, whether PHP 7.3/7.4 or PHP 8 is used.

The [manual page](https://php.net/function.http-build-query) states that the 3rd parameter `$arg_separator` is default `null` and the function then outputs the [arg_separator.output](https://www.php.net/manual/en/ini.core.php#ini.arg-separator.output), but on PHP 7 it is just empty when passing `null`. With PHP 8, the separator is used as described.
If 3rd parameter omitted, it is the separator for all PHP 7 and 8. 

Causes problems when the 3rd parameter is supposed to be default but 4th parameter needs to be passed on PHP 7.

Whatever version is intended, at least the difference should be documented in the manual page.

**Comment by damianwadley** [comment]
This may have been an unintentional bug fix during [af80d8a](https://github.com/php/php-src/commit/af80d8a14e5540a151e2b40f165ebe122467484b#diff-74ad62456f48fb4763daf08798ff4933c138058b59862e9e0703988f828e31a8), where the separator was changed from a Z_PARAM_STRING to a Z_PARAM_STRING_OR_NULL.

How I read the code, the intended behavior was always that null means the default value of the arg_separator.output, but in PHP <=7.4 a null would have been coerced to a string.

On a brief side note, there's also an interesting nuance here: if you pass an empty string as the separator then PHP will use that, but if you pass null and the arg_separator.output is an empty string then that will be ignored and `&` used instead.
https://3v4l.org/u4lMH

I don't know if there's value in adding this to the global changelog/8.0 migration guide at this point, but given that it had been broken since at least PHP 5, I think adding a note in the http_build_query changelog makes sense.

**Comment by R2116** [comment]
> How I read the code, the intended behavior was always that null means the default value of the arg_separator.output, but in PHP <=7.4 a null would have been coerced to a string.

That's how I would guess it, too. Would be nice to document the wrong behaviur PHP <= 7.4 in the manual page

**Comment by cmb69** [comment]
The point is that the `$arg_separator` parameter is properly nullable as of PHP 8.0.0, [like many other parameters of other functions](https://www.php.net/manual/en/doc.changelog.php).
