### ISSUE TITLE
ini_set() types for config keys

### ISSUE THREAD

**Issue by staabm** [php/doc-en#2295]
`ini_set` is defined as ` ini_set(string $option, string|int|float|bool|null $value): string|false`

is there a list somewhere which ini-key expect which type (2nd arg), like we have for curl here https://www.php.net/manual/en/function.curl-setopt for `ini_set`?

my goal is: I want to make phpstan aware which types are expected when, in a similar way [I did it for curl_setopt](https://github.com/phpstan/phpstan-src/pull/1719)

I don't necessarily need this list in the php manual. I am fine with scraping the sources or something.. just need a hint how to find out :)

**Comment by damianwadley** [comment]
You mean like the [List of php.ini directives](https://www.php.net/manual/en/ini.list.php) page?

That doesn't cover the fact that extensions can add settings too, though...

**Comment by staabm** [comment]
> You mean like the [List of php.ini directives](https://www.php.net/manual/en/ini.list.php) page?

I found this list already, but it does not include types per ini-key I am looking for.

**Comment by damianwadley** [comment]
The descriptions pages (eg. [core](https://www.php.net/manual/en/ini.core.php)) include types, however there isn't one single page describing all directives like that. And even if there was, it still wouldn't cover settings from extensions.

If you want to be sure of finding everything accurately, you could check out the php-src and grep it for `STD_ZEND_INI` - however that'd still leave you looking up function definitions to understand what they accept since definitions use setter callbacks and not type enums. Extensions problem again, but at least you'd be seeing the "core" extensions.

**Comment by staabm** [comment]
thx
