### ISSUE TITLE
imap_utf8 decode issues with 'á' maybe happend with another like 'éíóú'

### ISSUE THREAD

**Issue by uniauto** [php/doc-en#2336]
From manual page: https://php.net/function.imap-utf8

---
I found a issue when decoding string that contain 'á'.
It look like OK but its not. There issues because somehow the decoded 'á' =/= 'á'.
Example:

$mailSubject = '=?iso-8859-1?q?Albar=E1n_=28=2C_S=2EL=2E=29?=';
$imapDecodedSubject = imap_utf8($mailSubject);
$iconvDecodedSubject = iconv_mime_decode($mailSubject, 0, "UTF-8");
var_dump($imapDecodedSubject); // "Albarán (, S.L.)"
var_dump($iconvDecodedSubject); // "Albarán (, S.L.)"
// They look like the same, but they are not!
var_dump( mb_strlen($imapDecodedSubject) ); // 17
var_dump( mb_strlen($iconvDecodedSubject) ); // 16
var_dump( $imapDecodedSubject == $iconvDecodedSubject ); // false !!
var_dump( mb_strpos($imapDecodedSubject, 'á') ); // false !!
var_dump( mb_strpos($iconvDecodedSubject, 'á') ); // 5

**Comment by damianwadley** [comment]
PHP offloads this work to an IMAP C library typically named like c-client or cclient. Do you have any idea which you're using? It matters when PHP was compiled and not when it runs.

This appears to be somewhat deliberate, as if you don't have a "new" version of this library (when PHP is compiled) then it uses an older pattern where it deliberately asks the library to decompose UTF-8 characters: meaning that `a`-with-accent is actually encoded as `a` plus a combining accent. As two separate code points.

Which also means that this is technically valid behavior - it's just that you're not getting character sequence you expect. Is this causing an actual problem for you? Because anything compliant with Unicode should be able to accept `a` + combining accent just as well as an `a`-with-accent.

**Comment by Girgias** [comment]
Closing as this looks more like discovering the joys of encoding and unicode
