### ISSUE TITLE
Description states callable can be used as type declaration, but that's not true for class properties 

### ISSUE THREAD

**Issue by robopzet** [php/doc-en#2376]
From manual page: https://php.net/language.types.callable

---
From the text it looks like `callable` is a normal type like any other.  But on code that defines a class property typed `callable` the parser fails. For example this is invalid (at least in PHP 8.1.6):

```php
class X {
    /**
     * The target to call.
     */
    private readonly callable       $tgt;
}
```

**Comment by Girgias** [comment]
> 

It is a "normal" type for all intent and purposes. It just has a limitations on class properties due to technical scope implementation details.

Type declarations are covered in depth on the related page.

If you want to store a callable on a class property use ``Closure`` as any callable can be converted to a closure.

**Comment by robopzet** [comment]
I just thought it would be helpful if the description of `callable` includes the exceptions from other types.

> It just has a limitations on class properties due to technical scope implementation details.

As a user of PHP I'm interested in the language specification. Perhaps there could be a page that describes which parts of the specification are undefined and implementation specific.
