### ISSUE TITLE
IntlDatePatternGenerator returns wrong german Pattern

### ISSUE THREAD

**Issue by manuelKruesi** [php/doc-en#2571]
The Pattern Generator return a wrong German format when requesting Day of Week (textual) and in number format (eee d)
This is the returned pattern:
Mo., 19
Instead it should be:
Mo, 19
Am I doing something wrong or should this be resolved? 

From manual page: https://php.net/class.intldatepatterngenerator

---

**Comment by damianwadley** [comment]
IntlDatePatternGenerator and the intl extension is powered by the ICU Project. They are the ones who determine whether the month is `Mo.` or `Mo`, and it may change over time.
https://icu.unicode.org/

Has this value changed recently for you? What version of ICU are you using, as reported by `phpinfo`?

**Comment by manuelKruesi** [comment]
Thank you for clarification. Since this patterngenerator has been introduced recently, i only started implementing it, so no comparison to older data is possible. I am using the following versions:

ICU version | 66.1
ICU Data version | 66.1
ICU Unicode version | 13.0

**Comment by damianwadley** [comment]
Using ICU 71, `eee` shows me `Mo`.

Update your ICU library, or (maybe) try a different pattern like `eeeeee`, or (if I read this correctly) use a specific "de" sublocale that is more appropriate to your region which may format differently.

**Comment by manuelKruesi** [comment]
thank you for your answer. I am also getting Mo with "eee" provided, the problem is the combination of "eee d". What output does this pattern produce with ICU 71? Thank you for your help!

**Comment by damianwadley** [comment]
Interesting that it does add a period when combined with other values. But it isn't just IntlDatePatternGenerator as using `eee d` for the pattern directly with IntlDateFormatter has the same result.

I don't know why ICU decided to have this behavior, and I'm not really sure what else I can tell you...

Do you really _need_ to remove that period?

* If it's because ICU is wrong and they are formatting the date in a way that is incorrect for the locale, then I'd suggest submitting a bug report to them with your own locale (there are multiple "de" locales) and an explanation why there shouldn't be a period.
* If you don't want the period merely because you don't want the period then I would reconsider and trust that ICU is making the correct decisions. Because it's clear from "eee" versus "eee d" that there was some specific decision made that a period should be deliberately added in some cases.
