### ISSUE TITLE
Login Problem My Database 

### ISSUE THREAD

**Issue by MushifJutt** [php/doc-en#2665]
From the manual page: https://php.net/session.security

---[http://localhost/Groceries_Sales_and_Inventory_System/login.php](url)
Sir Issue Is Don't Login For Pleses set it

**Comment by MushifJutt** [comment]
send my problem solution to My Gmail Please quickly

**Comment by damianwadley** [comment]
Sorry, but your problem does not imply a bug in PHP itself.  For a list of more appropriate places to ask for help using PHP, please visit http://www.php.net/support.php as this bug system is not the appropriate forum for asking support questions.  Due to the volume of reports we can not explain in detail here why your report is not a bug.  The support channels will be able to provide an explanation for you.

Thank you for your interest in PHP.
