### ISSUE TITLE
PDO and `START TRANSACTION WITH CONSISTENT SNAPSHOT` in MariaDB

### ISSUE THREAD

**Issue by someniatko** [php/doc-en#2729]
MariaDB supports the following syntax for starting the transaction in a "snapshot" mode somewhat similarly to how MS SQL Server does it:

`START TRANSACTION WITH CONSISTENT SNAPSHOT`
https://mariadb.com/kb/en/enhancements-for-start-transaction-with-consistent-snapshot/

I would like to know how to achieve that using PDO. I have not found the related attribute for the "PDO_MYSQL" driver documentation here https://www.php.net/manual/en/ref.pdo-mysql.php, do I miss anything?

**Comment by damianwadley** [comment]
PDO's `beginTransaction` is simply a convenience function that will execute a `START TRANSACTION` statement. You can certainly start a transaction manually instead of calling that function.

**Comment by someniatko** [comment]
@damianwadley Thank you, it seems that what's I'll have to use if this is not planned. Although, perhaps a driver-specific flag would be more convenient.

By the way, `mysqli` supports this behavior as a flag when beginning a transaction https://www.php.net/manual/en/mysqli.begin-transaction.php

**Comment by damianwadley** [comment]
I certainly won't say that this could never happen, however the main issue I see is that PDO is designed to support multiple database systems and everybody does SQL differently; for example, MySQL has [3 "characteristics"](https://dev.mysql.com/doc/refman/8.0/en/commit.html), PostgreSQL has [quite a few possible combinations of options](https://www.postgresql.org/docs/current/sql-start-transaction.html), and SQL Server [only does "marks"](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/begin-transaction-transact-sql?view=sql-server-ver16). An implementation to customize the start of the transaction would probably end up as some key/value array of desired options, with each key being a constant defined on the PDO class (as with other constants).

But then there's the issue of userland implementation. That would be difficult too, as you wouldn't be able to set the beginTransaction flags in a database-agnostic way: between the three examples cited above, none of them support even one common option - and PDO has 11 different official drivers. Like, what should happen if you set `READ ONLY` but the code is executing against SQL Server?

Database query abstraction is a very, very difficult thing to get right - partly because the SQL "standard" is comically minimal, and partly because so many vendors just flat-out disregard parts of it. It's easy to not realize this when established languages like PHP have the benefit of people who are invested in dealing with those difficulties (such as the Doctrine folks) so that regular developers like us don't have to. But even then, you invariably have to give up on some functionality that you could have made use of with some hardcoded SQL.

But I'm digressing, and will stop myself before I go into a _real_ rant about the perverseness of insisting on abstracting out SQL queries. (And I do specifically mean the queries themselves.) Point is, IMO this is just one of those times when you need to just write some raw SQL.

If only the PDO drivers were designed as subclasses...

> By the way, `mysqli` supports this behavior as a flag when beginning a transaction

Given everything above, the answer to that shouldn't be surprising: mysqli can do it because it's specifically written for MySQL.

**Comment by Girgias** [comment]
> If only the PDO drivers were designed as subclasses...

I mean we have https://github.com/php/php-src/pull/11740, which sadly didn't make 8.3 due to the confusing PHPDBG tests failures.
