### ISSUE TITLE
openssl_pkcs7_encrypt not work

### ISSUE THREAD

**Issue by keradach** [php/doc-en#2857]
From manual page: https://php.net/function.openssl-pkcs7-encrypt

---
i'm use php 7.4.33
but openssl_pkcs7_encrypt return failed.i don't know propblem.

**Comment by damianwadley** [comment]
It's going to be really hard for us to know what the problem is either.

Given that this is just a bug tracker and thus not a suitable place to help you troubleshoot your code, consider asking on a programming forum, StackOverflow, or [a mailing list or other support group](https://www.php.net/support.php).
For the best chance at solving your problem, please consider [these tips from StackOverflow on how to ask a good question](https://stackoverflow.com/help/how-to-ask).
