### ISSUE TITLE
PHP6407

### ISSUE THREAD

**Issue by Timbuktu1982** [php/doc-en#2871]
Methods with the same name as their class will not be constructors in a future version of PHP.PHP(PHP6407)
From manual page: https://php.net/migration70.deprecated

Hi there,
why does this deprecation also refer to the uses of traits?

**Comment by damianwadley** [comment]
The page doesn't mention traits. Do you mean, why does the deprecation also include methods defined by traits?

```php
trait FooTrait {
    public function Foo() { }
}

class Foo {
    use FooTrait;
}
```

Because a method defined by a `use`-d trait is the same as if that method was defined directly in the class itself; the above code _would_ use FooTrait's `Foo` method as the constructor.
