### ISSUE TITLE
Exponentiation operator should always indicate it is only available starting with 5.6

### ISSUE THREAD

**Issue by lxvi** [php/doc-en#3171]
In the following three pages, there is no indication that the exponentiation operator '**' is only available starting with version 5.6 (and that pow() should be used in earlier versions)
https://www.php.net/manual/en/function.pow.php
https://www.php.net/manual/en/language.operators.arithmetic.php
https://php.net/language.operators.precedence

---

**Comment by damianwadley** [comment]
As a whole, the manual currently only speaks to PHP 7 and later.
https://www.php.net/manual/php5.php

Zend's copy of the PHP 5 manual does mention that `**` was introduced in 5.6.
https://php-legacy-docs.zend.com/manual/php5/en/function.pow
https://php-legacy-docs.zend.com/manual/php5/en/language.operators.arithmetic
(the [operator precedence page](https://php-legacy-docs.zend.com/manual/php5/en/language.operators.precedence) doesn't, which is fine because that's not where it should be documented anyway)
