### ISSUE TITLE
Links embedded in PHP 5 feature announcement are broken

### ISSUE THREAD

**Issue by yadaiio** [php/doc-en#3280]
Hello everyone, I was working on the documentation for one of our projects where we use a link to highlight the [addition of multicast socket options in PHP 5.4](http://php.net/manual/en/migration54.global-constants.php). It seems like this link and all the other forwarding links on your [release page](https://www.php.net/releases/5_4_0.php) are currently not working though. 

Even though PHP 5 is no longer supported, I wonder if this was an intentional choice or did it break in the meantime. If it was intentional, do you happen to have any alternative resources I could refer to instead of http://php.net/manual/en/migration54.global-constants.php?

**Comment by damianwadley** [comment]
Yes, removing information about PHP 5 was intentional: maintaining it was a chore, and its increasingly out-of-date information was becoming a risk to developers looking for documentation relevant to their needs.
https://www.php.net/manual/php5.php

zend.com maintains a copy of the PHP 5 docs, which you should be able to link to for the foreseeable future.
https://php-legacy-docs.zend.com/manual/php5/en/index

Linking to pages snapshotted by archive.org is another option, too.

**Comment by yadaiio** [comment]
Hey @damianwadley, thank you for this information. Good to know there are other ways for linking old PHP versions. I will choose zend.com for linking. Thank you so much. 👍
