### ISSUE TITLE
PHP chdir not working when the php server script is called via JS XMLHttpRequest()

### ISSUE THREAD

**Issue by bquimby1** [php/doc-en#3305]
From manual page: https://php.net/faq.html
I know this is something silly.  I have several AJAX transactions working perfectly but this is the first one I've tried to implement one on this site.  The JS request makes it to the server just fine but when the server does a chdir it stops.  It doesn't throw an error, it simply stops dead in it's tracks.  I can run the server from the command line with no problems.  I don't believe that there are any permissions issues with the server as I can submit forms (and chdir() )with no problems.  Any ideas?
---

**Comment by damianwadley** [comment]
Sorry, but your problem does not imply a bug in PHP itself.  For a list of more appropriate places to ask for help using PHP, please visit http://www.php.net/support.php as this bug system is not the appropriate forum for asking support questions.  Due to the volume of reports we can not explain in detail here why your report is not a bug.  The support channels will be able to provide an explanation for you.

Thank you for your interest in PHP.
