### ISSUE TITLE
Why is documentation so 'lacking' for PHP source code?

### ISSUE THREAD

**Issue by risharde** [php/doc-en#3479]
Good day, I must partially apologize for this post but I'm amazed.
As a developer that uses PHP for web development, I assumed that PHP was an organized programming language - in fact I got into PHP due to it's popularity partially of which seemed to be related to the simplicity of the language and the documentation for PHP functions etc.

However, taking the leap to look into possibly contributing to the source and venturing into opcache because I was rather curious of it's workings - I realized I had assumed too much - the documentation is severely lacking. 

I could understand if this documentation was for perhaps a new language that's only been out for a year, but I am quite amazed at how lacking the documentation is for the source code. It gives me the impression that whomever  (plural) who wrote this module did not get paid and so they wrote the code and just left out vital documentation.

I would love to help with this but at the moment, I'm struggling to understand being new to C how the inner workings of the Zend Engine work by messing around with opcache. Maybe if I get better at it I can help but I really wish some love and attention was paid to documenting code - I'm wondering if this would help encourage contributors to work on PHP without the dramatic learning curve of figuring out thousands of lines of code (seeing a few PHP coders talking about opcode etc and mentioned 10 years of working with PHP - I can see why it would take 5-10 years to become good at this without documentation).

P.S To those who have added documentation / comments to their code, thank you for your priceless contributions!!!!!

**Comment by damianwadley** [comment]
Regular PHP developers just don't care about the source code like you and I do. It's not relevant to what they do. Same for Javascript developers not caring about V8/Node, or Python developers caring about C, or developers of compiled languages caring about how the compiler works. If a PHP developer want to learn about the array_map function, information about the internals of macros and hashtables and whatever is just going to get in the way of that.

But there is documentation for much of PHP's internals - you just have to go somewhere else for it.
https://www.phpinternalsbook.com/
It's not going to be enough to teach you up to the same level as a "core" developer, but it's a good start.

> I could understand if this documentation was for perhaps a new language that's only been out for a year, but I am quite amazed at how lacking the documentation is for the source code.

I feel the opposite of that: if a new language came out now then I'd expect (to some degree) that they _would_ have documentation about how to develop with its internals, while the older languages would likely have _less_ documentation because so much time has passed.

Which is PHP's case. It began in the early 90s, which means it's about _30 years old_. (Yes, there's a whole generation of software developers out there who were born after PHP was created.) And a whole lot has happened in that time frame. In fact, from where I sit, PHP's internal development only seems to be increasing: every year we keep getting more RFCs, longer discussions, larger features... That's a lot of non-trivial changes to the source code happening with each version.

And don't forget that the nature of documentation, at least the complicated big-picture stuff that requires explanations, almost always has it separate from the source. A separation that makes it very hard to keep up to date with changes. So what naturally happens is that documentation grows out of date with its source - and inaccurate docs are worse than no docs.

Managing documentation of software in a way that doesn't easily get out of date is tough problem that nobody has solved.

> I would love to help with this but at the moment, I'm struggling to understand being new to C how the inner workings of the Zend Engine work by messing around with opcache.

Maybe opcache isn't the best place to start? Don't dive into the deep end of the pool when you're only just now learning to swim.

Take a look at the simpler extensions like ext/date or ext/filter, or the different parts of the monolith that is ext/standard, or perhaps ext/tokenizer if you're interested in that sort of stuff. Dive as deep as you want into their details. Use those to get yourself a good start with an understanding of the more common aspects of PHP. When you have that, tackling larger pieces with more complicated moving parts, such as a good number of the files in Zend/, will be easier because there will be much less unfamiliar stuff to have to deal with at one time.

---

Closing because there's really not much we can do about this in the regular docs. I'm sure other people will give their 2¢ too.

**Comment by Girgias** [comment]
Note, there is a project to write "new" docs which live in the php-src repo: https://php.github.io/php-src/index.html
