### ISSUE TITLE
Move `implode()` to array section and/or cross-ref.

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#3864]
This is from note 129797 whose writer does not have GitHub:

> This will probably be deleted, but it feels like this function would be better suited under the array function section since the input is an array.  
>
> This is based on the key input object for the function: an array.  
> 
> If we base categorization of built-in functions on output, then a bunch of array functions could probably move to other sections of the documentation, too.  
> 
> Alternatively, these could be cross-listed or a redirect could be added to one page or the other. 

From manual page: https://php.net/function.implode

---

**Comment by kamil-tekiela** [comment]
I've thought about it and my decision is against this change. 

The classification is neither based on the input nor the output parameters, but rather logical connection. It's much more common to think of it as splitting and merging strings rather than merging and splitting an array. It makes more sense for this function to be listed with other string functions. It's also not a meaningful change, especially not after many years of status quo.
