### ISSUE TITLE
Use `jing` to indicate RelaxNG schema conformance issues instead of libxml

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#3912]
This is because libxml gives crappy error messages for RelaxNG failures.

It would be good to have a CI setup, it seems there is a package for Ubuntu (better than Fedora where I needed to self compile) `sudo apt install jing` so we would need to improve the CI pipeline to run this and pass the generated `.manual.xml` from `doc-base`, but then you get _huuuuuge_ line numbers as we are not working on a per-file basis.

Might be possible to just check individual files, but no idea if that works with entities.

**Comment by cmb69** [comment]
Locally (for me), it wouldn't be a problem to jing-validate the whole file. It seems to be even an improvement over the old libxml doctype validation. For CI, it might be good enough as well.

Regarding the installation; can't we just use the jing.jar? I've dropped the file into doc-base, and that works fine for me. Since the jar is only ~700MB we may even commit it to doc-base so that it's available to everyone right away. Tried with downloads from https://code.google.com/archive/p/jing-trang/downloads and https://github.com/relaxng/jing-trang/releases/tag/V20220510. The license appears to be MIT-like, so that shouldn't be an issue.

**Comment by Girgias** [comment]
Right, but then people need Java installed :D

But I didin't realise the jar was that small. I did check that validating individual files is still no go because of entities but minor issue that could be fixed by doing some str_replace before passing it to jing.

**Comment by Girgias** [comment]
This has now been done, so closing.

**Comment by athos-ribeiro** [comment]
Hi,

would you consider a patch to use a system installed `jing`instead as initially proposed?

Also, as discussed in https://github.com/php/doc-base/pull/170#pullrequestreview-2392528929,

> I think we also should add a license file for jing. The downloads have doc/copying.html, were we like should strip the <h2>Third-party JARs</h2> part.

Did we miss including a license for the embedded jar file?

**Comment by cmb69** [comment]
I don't think it makes much sense to use a system jing, if doc-base already had shipped jing, but I'm fine with that.

And yes, we *need* to add a license file (or clearly document the license terms elsewhere).

**Comment by Girgias** [comment]
Right the licence, forgot about this.

But Fedora does not have Jing in any system packages. And considering this is what I use and needed to compile it (which is the committed version) I don't really see a benefit.

**Comment by athos-ribeiro** [comment]
Thanks for the quick replies!

Ack. The reason I asked was due to the provenance of the binary file in the repository (I suppose there is no verification for that ATM?)

It is indeed straightforward this for re-distribution purposes though! And thanks for considering adding the license there as well
