### ISSUE TITLE
Copyright page's distribution notification requirement may conflict with CC-BY 3.0 License

### ISSUE THREAD

**Issue by HiroKws** [php/doc-en#4130]
The current copyright page for the PHP Documentation includes a requirement to notify doc-license@lists.php.net before redistributing or republishing the documentation. This appears to conflict with the terms of the Creative Commons Attribution 3.0 License under which the documentation is released.

## Current Situation
The copyright page states:
> If you are interested in redistributing or republishing any part of this manual with or without modification, or if you have any questions, please contact the copyright holders at doc-license@lists.php.net.

## Issue
While the intent may be to track usage, this requirement appears incompatible with CC-BY 3.0 because:

1. Section 4(a) of CC-BY 3.0 explicitly prohibits imposing "any terms on the Work that restrict the terms of this License or the ability of the recipient of the Work to exercise the rights granted"

2. The license is designed to be "worldwide, royalty-free, non-exclusive, perpetual," and a pre-notification requirement creates an additional barrier to free redistribution

## Suggested Resolution
Consider modifying the copyright page text to make notification optional rather than required. For example:
> While not required by the license, we appreciate being notified at doc-license@lists.php.net if you redistribute or republish the documentation.

This would:
- Maintain alignment with CC-BY 3.0 terms
- Preserve the spirit of open sharing
- Still encourage community engagement
- Avoid potential legal conflicts with the license

P.S. I am not a skilled English writer, so I had Claude review and generate this issue text for me.

**Comment by Girgias** [comment]
Yeah I don't think requiring the notification makes a lot of sense... I probably would just remove it and maybe even archive the mailing list.

Opinions @jimwins ?

**Comment by HiroKws** [comment]
I would add that the mailing list is currently not acting to receive communications from non-subscribers, as it is set up to require subscription in order to post.

**Comment by jimwins** [comment]
Yes, I think it makes sense to just remove this. The "PHP Documentation Group" is an ill-defined entity, anyway, and perusing the very few requests that have come into the doc-license@ list in the last 10 years is a pretty good indication that nobody is even responding to questions. I'm having a hard time coming up with a scenario where the documentation could be used in some nefarious way, where someone would care, and where someone would really have standing to do anything about it.

**Comment by KERNAMON** [comment]
### Pre-Notification Requirement?

The CC-BY 3.0 license is designed to be open, allowing users to freely share, modify and redistribute the licensed material **_without additional restrictions_**. The key point from Section 4(a) of CC-BY 3.0 is that it prohibits imposing additional terms that could restrict the exercise of the rights granted by the license.

The pre-notification requirement as stated on the PHP documentation’s copyright page **may be seen as such an additional term** (in this case, as a restriction). Requiring individuals or organizations to notify the PHP documentation team before redistributing or republishing could be interpreted as a restriction on the free exercise of the rights granted by the [CC-BY 3.0](https://creativecommons.org/licenses/by/3.0/) license. This would conflict with the royalty-free, non-exclusive and perpetual nature of the license.

### Possible Resolution
The proposed solution to make notification optional rather than required is a logical and compliant adjustment with the terms of the CC-BY 3.0 license.

### Revised Text Example:
"While not required by the CC-BY 3.0 license, we appreciate being notified at [doc-license@lists.php.net](mailto:doc-license@lists.php.net) if you redistribute or republish the documentation."


The above revised and suggested text still maintains full compliance with the CC-BY 3.0 terms, as it no longer imposes a possible mandatory requirement for pre-notification. Encourages community engagement by making notification optional, which allows the PHP documentation team to track usage and contributions while keeping the process voluntary.

Preserves the spirit of open sharing, ensuring that users are free to distribute and modify the documentation without unnecessary barriers. Avoids potential legal conflicts by not imposing any (possible) restrictions that could be seen as violating the CC-BY 3.0 license.

### The Devil in The Details...
![php-net-copyright-and-license](https://github.com/user-attachments/assets/9cea2dd9-602e-4d6f-b9b2-58c33b040c3e)

The devil is in the details, no doubt... as it is seen on the screenshot taken on the December 13th, 2024, the word "**_and_**" provides what seems to be the legal innocence of the PHP Group. From a legal standpoint, "**and you have questions**" **_adds a condition_**, in other words: it only suggests that **IF** someone has questions regarding the redistribution or republishing, **_then_** (and only then, in that case cenario) that very same someone can or may contact the Copyright holders.

### CONCLUSION:
So it seems that up to this date, php.net and its Copyright holders did not infringe upon the legal specifications of the Creative Commons license in question.

*** Please be advised that we are not lawyers. ***

**Comment by Girgias** [comment]
The prior discussion of this PR was to *remove* the notification all together. So I don't think improving the wording makes much sense.
