### ISSUE TITLE
fseek() documentation is confusing and incomplete, and fseek() return codes are backwards

### ISSUE THREAD

**Issue by Raven-Singularity** [php/doc-en#4255]
# My experience learning fseek() from the documentation

From manual page: https://php.net/function.fseek

This is my first time using `fseek()`, so it's definitely possible I don't know what I'm doing, or am misreading the documentation.

Documentation says:

    offset
    The offset.
    
    To move to a position before the end-of-file, you need to pass a negative value in offset and set whence to SEEK_END.
    
    whence
    whence values are:
    
    SEEK_SET - Set position equal to offset bytes.
    SEEK_CUR - Set position to current location plus offset.
    SEEK_END - Set position to end-of-file plus offset.

It seems to be telling me to do this to seek 2KB before the end of the file:

`fseek($File_Handle, -2048, SEEK_END);`

However, this always returns `FALSE` for me. 

The `fopen()` before this produces no error.
The file is 1.8MB, so there is definitely data to seek in.
I can read from the file with `fgets()` or `fread()` just fine.

How do I seek to 2KB before the end of a large file?

Also, why is the word "wence" being used here?
That is horrifically confusing wording for this context.  I had to read that section 4 times to have a clue what it was even talking about.

Trying to debug this issue... trying a bunch more things out now.

These commands also fail for me:

    fseek($File_Handle, -2048, SEEK_END);
    fseek($File_Handle, 2048, SEEK_END);
    fseek($File_Handle, 0, SEEK_END);
    fseek($File_Handle, 0);

But very strangely, this command works, but starts me at position `0`:

    fseek($File_Handle, -2048);

I am at a loss for how I can be getting results like these, they seem completely arbitrary.  No warnings, notices, or errors are being thrown, the function is just returning `FALSE`.

This command shows a normal file:

    fstat($File_Handle);

It has `[size] => 1822525`

## Problem now understood

Okay, figured out the problem.  `fstat()` is not returning `FALSE`, it is returning `0` which is evaluating to `FALSE`.

Why in the world does `fseek()` return `0` (`FALSE`) on success, and `-1` (`TRUE`) on failure?

That is nonsensical and broken.

## Improvements to documentation

**At the very least update the documentation to specify this entirely crazy behaviour exists!**

This is definitely _not_ enough documentation:

    Upon success, returns 0; otherwise, returns -1.

The user should be informed that this function's return values are completely backwards from the expected return format of every other function in PHP.

This is way worse than all those functions that return `FALSE` on errors and `0` or above on success -- because PHP documentation actually mentions that special case in an info box: "`This function may return FALSE on error but may also return 0 that evaluates to boolean FALSE`", or whatever the exact wording is.

**This function needs a large warning that it returns backwards return values from what is expected of PHP functions, and an explanation of _WHY_ it chose to do things in this backwards way.**

The basic error checking code I was using (like I always use) fails because of this absurdity:

    if (!fseek($File_Handle, 0)) { die("Could not seek in file."); }

What a royal waste of time...

**Comment by kamil-tekiela** [comment]
I will take a look to see if I can write a PR to improve it, but I would just like to make some remarks first. 

> Also, why is the word "wence" being used here?

I believe you meant "whence" which is an archaic English word. It's used here because that's the parameter name. As to why it's the parameter name, I can't say for sure, but this word is used quite a lot in the PHP source code so it probably made sense for the developer of this function to use it here. Interestingly, it seems like in C it's actually called `origin` (https://cplusplus.com/reference/cstdio/fseek/) so I am not sure why PHP uses a different name. 

> That is nonsensical and broken.

A lot of the C-style functions are nonsensical because they are almost identical ports of the C functions. If you come from C language and you see a function that is named the same way and does the same thing, you expect that it returns the same values. Sure, it makes no sense from a PHP perspective, but that's just how these functions came about in PHP. Even the PHP style [`SplFileObject::fseek`](https://www.php.net/manual/en/splfileobject.fseek.php) retains this behaviour. 

When using these functions in PHP you should be writing them C-style, e.g. 
```
if (fseek($fp, 0)) {
    // Error happened here
}
```
What's most ridiculous about these functions is that you have to check the return value to know if it failed or not. In the PHP world you should never need that as PHP has a concept of exceptions which should be triggered on failure. 

> This function needs a large warning that it returns backwards return values from what is expected of PHP functions, and an explanation of WHY it chose to do things in this backwards way.

That sounds like a good idea. 

---- 

You say:
>These commands also fail for me:

But once we understand that they don't actually fail, I think the description becomes pretty clear. 

> It seems to be telling me to do this to seek 2KB before the end of the file:
>
>     fseek($File_Handle, -2048, SEEK_END);

It seems to me like you're right.

**Comment by Raven-Singularity** [comment]
@kamil-tekiela Thanks a lot!
