### ISSUE TITLE
About array_filter method 

### ISSUE THREAD

**Issue by zigzagdev** [php/doc-en#4284]
# Question

when i use method array_filter in Laravel, array index is missing in new array. So i use array_values method and fix that missing array index circumstance.
Could you please tell me why array_filter method make an array index missing . I think few people need only the index number of an array.

**Comment by damianwadley** [comment]
Because the "list" `array("a", "b", "c")` is actually a "dictionary" `array(0 => "a", 1 => "b", 2 => "c")`, and if that was filtered to remove "a" then a result of `array(0 => "b", 1 => "c")` would be weird.
Preserving the keys makes it much easier to explain how it would work with arrays that only have string keys (nothing happens to the keys at all) and means no question about what would happen with arrays containing mixed string and integer keys (would the integer keys be preserved or not?).
