### ISSUE TITLE
8.4 fgetcsv,... missing deprecated info about $enclosure

### ISSUE THREAD

**Issue by kkmuffme** [php/doc-en#4327]
https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_proprietary_csv_escaping_mechanism

no mention of that in https://www.php.net/manual/en/function.fgetcsv.php even though other PHP 8.4 things are there

**Comment by kamil-tekiela** [comment]
I can see it clear as day:

> Warning
As of PHP 8.4.0, depending on the default value of escape is deprecated. It needs to be provided explicitly either positionally or by the use of [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments).

I am closing this issue as invalid since it's definitely there.
