### ISSUE TITLE
PHP Pathinfo() function - returns

### ISSUE THREAD

**Issue by markem** [php/doc-en#798]
From manual page: https://php.net/function.pathinfo

The online manual does not say it - but shouldn't the pathinfo() function return a false if there is a problem (like - no file given or file not found)? Just wondering. :-)

**Comment by sy-records** [comment]
https://3v4l.org/Rbrfp

It will always return the output array or string.

```php
array(2) {
  ["basename"]=>
  string(0) ""
  ["filename"]=>
  string(0) ""
}
```

**Comment by markem** [comment]
Ok. However, about a year ago, I read that PHP was trying to make everything conform to "1)Return actual value" or "2)Return FALSE". So the fact that if I call PathInfo() like this:

$info = pathinfo();

Should it not return a FALSE return so you know it did not work?  Seems like it would be a lot easier to do than having to test for a blank string. Again - just wondering.

Currently you'd have to do something like this \: 

     if( strlen($info = pathinfo()) < 1 ){...}

Instead of \:

    if( ($info = pathinfo()) === false ){...}

**Comment by cmb69** [comment]
If you're calling an internal function with the wrong number of arguments, or with unsupported argument types, the [behavior is undefined](https://www.php.net/manual/en/functions.internal.php). (prior to PHP 8.0.0, usually you get a warning, and the function returns NULL; as of PHP 8.0.0, usually the function throws a TypeError) There is no need to catch that, since it's a programming error anyway, and should be fixed.
