### ISSUE TITLE
Returning wrong year

### ISSUE THREAD

**Issue by cmdejong** [php/doc-en#826]
From manual page: https://php.net/function.date

---

Dear all,

I used your function date in echo date(“Y-W”, strtotime(“2021-01-01"));
I expected 2020-53 but instead, I got 2021-53.

I'm working in PHP version 7.3.11

Thank you in advance,

Developer at Digitaal Kantoor Gouda

**Comment by kamil-tekiela** [comment]
Please explain why you expected `2020` for the date in year `2021` when using the `Y` parameter? By the looks of it, I think you meant to specify the format as `o-W`, since `Y-W` doesn't make much sense. I am closing this incident as I don't see any PHP documentation bug here. Both are clearly documented on https://www.php.net/manual/en/datetime.format.php, but if you think something is not documented properly, please explain it clearly.

**Comment by cmdejong** [comment]
Thanks for the fast reply. I wasn't aware of the existence of o-W.
